####################################
server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: 
          searchPaths: mortgage-customer-service, mortgage-customer-account-service
          username:
          password: